/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 chair1.gltf --transform
Author: a.shevchuk (https://sketchfab.com/alex.shevchuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basket-swing-chair-92463f2b44624180a4ed8488ce08eb83
Title: Basket Swing Chair
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/chair1-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.part1_chair1_0.geometry}
        material={materials.chair1}
      />
      <mesh
        geometry={nodes.part2_chair1_0.geometry}
        material={materials.chair1}
      />
      <mesh
        geometry={nodes.part4_chair1_0.geometry}
        material={materials.chair1}
      />
      <mesh
        geometry={nodes.part5_chair1_0.geometry}
        material={materials.chair1}
      />
      <mesh
        geometry={nodes.part6_chair1_0.geometry}
        material={materials.chair1}
      />
      <mesh
        geometry={nodes.part7_chair1_0.geometry}
        material={materials.chair1}
      />
      <mesh
        geometry={nodes.part8_chair1_0.geometry}
        material={materials.chair1}
      />
      <mesh
        geometry={nodes.cushion_Cushion_0.geometry}
        material={materials.Cushion}
        material-color="#c56e33"
      />
      <mesh
        geometry={nodes.basket_chair1_0.geometry}
        material={materials.chair1}
      />
    </group>
  );
}

useGLTF.preload("/chair1-transformed.glb");
